catalog/urls.py
from django.urls import path


from . import views
from .apps import CatalogConfig
app_name = CatalogConfig.name

urlpatterns = [
    path('', views.ProductListView.as_view(), name='home_page'),
    path('catalog/', views.CatalogListView.as_view(), name='catalog'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='Name')
    description = models.TextField(verbose_name='description')
    image = models.ImageField(upload_to='products/', null=True, blank=True, verbose_name='image')
    purchase_price = models.DecimalField(max_digits=8, decimal_places=2)
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='date_of_creation')
    last_modified_date = models.DateTimeField(auto_now=True, verbose_name='last_modified_date')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

catalog/views.py
from django.shortcuts import render
from catalog.models import Product

from django.views.generic import ListView


# Create your views here.
class ProductListView(ListView):
    model = Product
    template_name = 'catalog/index.html'

class CatalogListView(ListView):
    model = Product
    template_name = 'catalog/catalog.html'

catalog/templates/catalog/catalog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'catalog/css/style.css' %}" rel="stylesheet">
    <title>Document</title>
</head>
<body>
    <header> 
        <a href="{% url 'catalog:home_page' %}"><img src="img/logo.svg" alt="logo"></a>
        <input type="text">
        <nav>
            <ul>
                <li>
                    <a href="{% url 'catalog:catalog' %}">Каталог</a>
                </li>
                <li>
                    <a href="#">Корзину</a>
                </li>
            </ul>
        </nav>
    </header>
    <section>
        <h1>Каталог</h1>
        <img src="img/product1.jpg" alt="желтое кресло">
        <h3>Кресло VILORA</h3>
        <p>Мягкое и уютное, аккуратное и стильное. Упругие подушки сиденья и приятная на ощупь ткань</p>
        <p>21 000</p>
    </section>
    <footer>
        <h4>Меню</h4>
        <nav>
            <a href="{% url 'catalog:home_page' %}">Главная</a>
            <a href="{% url 'catalog:catalog' %}">Каталог</a>
            <a href="#">Корзина</a>
        </nav>
        <h4>Контакты</h4>
        <a href="#">+7 908 800 80 80</a>
        <a href="#">help@interier.com</a>
        <img src="img/vk.svg" alt="логотип вконтакте">
        <img src="img/telegram.svg" alt="логотип телеграма">
        <img src="img/dzen.svg" alt="логотип яндекс_дзен">
        <form action="#">
            <p>Получайте наши новости и обновления</p>
            <input type="email">
            <button type="submit">Подписаться</button>
        </form>
    </footer>
</body>
</html>

catalog/templates/catalog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My site</title>
    <link href="{% static 'catalog/css/style.css' %}" rel="stylesheet">
</head>
<body>
    <header> 
        <a href="{% url 'catalog:home_page' %}"><img src="{% static 'catalog/img/logo.svg' %}" alt="логотип"></a>
        <input type="text">
        <nav class="menu">
            <ul>
                <li>
                    <a href="{% url 'catalog:catalog' %}" class="menu__link">Каталог</a>
                </li>
                <li>
                    <a href="#" class="menu__link">Корзину</a>
                </li>
            </ul>
        </nav>
    </header>

    <section>
        <h1 class="title">Все, чего заслуживает ваш дом</h1>
        <p class="text">Наша мебель — ваше отражение</p>
        <a href="{% url 'catalog:catalog' %}" class="link__catalog">Перейти в каталог</a>
    </section>
    <section>
        <h2 class="heading">Специальные предложения</h2>
        <img src="{% static 'catalog/img/product_name.jpg' %}" alt="желтое кресло">
        <h3 class="product__name">Кресло VILORA</h3>
        <p class="product__text">«Мягкое и уютное, аккуратное и стильное. Упругие подушки сиденья и приятная на ощупь ткань</p>
        <p class="product__discont">21 000</p>
        <p class="product_price">28 000</p>
    </section>
    <footer>
        <h4 class="footer__title">Меню</h4>
        <nav>
            <a href="{% url 'catalog:home_page' %}" class="footer__link">Главная</a>
            <a href="{% url 'catalog:catalog' %}" class="footer__link">Каталог</a>
            <a href="#" class="footer__link">Корзина</a>
        </nav>
        <h4 class="footer__title">Контакты</h4>
        <a href="#" class="footer__link">+7 908 800 80 80</a>
        <a href="#" class="footer__link">help@interier.com</a>
        <img src="{% static 'catalog/img/vk.svg' %}" alt="логотип вконтакте">
        <img src="{% static 'catalog/img/telegram.svg' %}" alt="логотип телеграма">
        <img src="{% static 'catalog/img/dzen.svg' %}" alt="логотип яндекс_дзен">
        <form action="#">
            <p class="footer__text">Получайте наши новости и обновления</p>
            <input type="email" class="footer__email">
            <button type="submit" class="footer__button">Подписаться</button>
        </form>
    </footer>
</body>
</html>